# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pacienta', models.IntegerField()),
                ('ime', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Preiskava',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta', models.CharField(choices=[('D', 'diagnostika'), ('CPAP', 'cpap'), ('BIPAP', 'bipap')], max_length=200)),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niv.Pacient')),
            ],
        ),
    ]
